name: test repo build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisite packages
        run: |
            sudo apt -y install reprepro gnupg ruby ruby-dev rubygems build-essential
            sudo gem install --no-document fpm
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build deb packages
        run: |
            make -C ytl-linux-customize deb
      - name: Build repository
        env:
            SKEY: ${{ secrets.SIGNING_KEY }}
        run: |
            echo "$SKEY" | gpg --import
            for dir in debs/ ytl-linux-customize/; do [ -d $dir ] || mkdir $dir; done
            find debs/ ytl-linux-customize/ -name '*.deb' | while read deb; do echo $deb; reprepro -b docs/reprepro includedeb foo $deb; done
