name: test repo build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisite packages
        run: |
            sudo apt -y install reprepro gnupg
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build repository
        shell: bash
        env:
            SKEY: ${{ secrets.SIGNING_KEY }}
        run: |
            printf "%s" $SKEY | wc
            printf "%s" $SKEY | base64 -d | gpg --import
            for f in debs/*.deb; do reprepro -b docs/reprepro includedeb foo $f; done
