name: test repo build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisite packages
        run: |
            sudo apt -y install reprepro gnupg
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build repository
        env:
            SIGNING_KEY: ${{ secrets.SIGNING_KEY }
        run: |
            echo $SIGNING_KEY | gpg --import
            for f in debs/*.deb; do reprepro -b docs/reprepro includedeb foo $f; done
